apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # Encode these values in base64 format
  mongodb-username: YmFja2VuZA==
  mongodb-password: YmFja2VuZA==
  mongodb-uri: bW9uZ29kYitzcnY6Ly9iYWNrZW5kOmJhY2tlbmRAY2x1c3RlcjAudzZ1NGEubW9uZ29kYi5uZXQ=
